In [1]:
import pandas as pd, numpy as np, math

#import data from the excel file and turns it into a dataframe
df = pd.read_excel('immersive23sepfiltered.xlsx')
#describes the data to give number of students - will need to do 'manual' counts for groups sorting sizes

## below Randomises the order of rows so that alphabetical names are reorgansied across rows and reindexed
dfrandomised = df.sample(frac=1)

#Sort as male and female so women are filtered in first to groups by cross section routine
dfrandomgendersort = dfrandomised.sort_values(by = 'Gender').reset_index(drop=True)

dfrandom = dfrandomgendersort

#Groups the data by course and gender into something we can work with
gendergroups = dfrandom.groupby(["PROGRAMME OF STUDY","Gender"]).groups#,"Gender"#

#gives a list of names to use as keys in the gendergroups dictionary
gender_keys_list = list(gendergroups)

#extract the variables for the numpy arrays I will need:
total_female_students = dfrandom['Gender'].value_counts().f
total_male_students = dfrandom['Gender'].value_counts().m
total_students = len(dfrandom.index)
total_programmes = len(dfrandom.groupby("PROGRAMME OF STUDY").groups)
total_gender_programmes = len(gendergroups)
#THIS WORKS!!!! DO NOT TOUCH!!!!
#i in and of itself is the key valueistelf - i.e the course and gender filter.
#this line prints the total number of students from counting the index
print(dfrandom['PROGRAMME OF STUDY'].describe())
print("\nTotal number of students: ", total_students)
print('Total number of programmes : ',total_programmes)
print("Total gender and programme groups: ",total_gender_programmes,'\n')
print("Total female students: ",total_female_students,'\n')
print("Total male students: ",total_male_students,'\n')
print('--------------------')


count                                                    36
unique                                                    2
top       Immersive Technologies (Virtual and Augmented ...
freq                                                     20
Name: PROGRAMME OF STUDY, dtype: object

Total number of students:  36
Total number of programmes :  2
Total gender and programme groups:  4 

Total female students:  15 

Total male students:  21 

--------------------


In [2]:
print("Please enter desired group size: ")
desired_group_size = input()
number_of_teams = (total_students/float(desired_group_size)) #using int rounds down the output number and converts string to integer for maths
remainder_people = total_students%int(desired_group_size)
print('Number of teams to be generated: ', int(number_of_teams))
print('With ',round(remainder_people), 'left to be paired. These people will be assigned to other groups automatically.')

Please enter desired group size: 
5
Number of teams to be generated:  7
With  1 left to be paired. These people will be assigned to other groups automatically.


In [3]:
df_full_array = dfrandom.to_numpy()
print(df_full_array.shape)
print(total_students)

(36, 10)
36


In [4]:
print(df_full_array[0])
print(df_full_array[19])

[1 'f' 'HARRIS' 'B' 'ri22586@bristol.ac.uk' 'ri22586' '\xa02340878'
 'Registered online' 'Immersive Arts (Virtual and Augmented Reality) (MA)'
 'Full Time - F85']
[1 'm' 'HIRUNWIWATKUL' 'POOM' 'nd22549@bristol.ac.uk' 'nd22549'
 '\xa02291908' 'Registered online'
 'Immersive Technologies (Virtual and Augmented Reality) (MSc)'
 'Full Time - F85']


In [5]:
testarray = [] #initiates a list so I can turn into an array later on

#iterate over filtered dataframe to pull out a list of values of students for each of the different groups
for i in gender_keys_list:
        select_course = gendergroups[i]
        testarray.append(select_course.values[0:])
        
#turn into a numpy array I can slice and reshape as needed
testarray
numpy_filtered_array = np.asarray(testarray, dtype=object)
print(numpy_filtered_array.shape)
print(len(testarray))




(4,)
4


In [6]:
print(len(numpy_filtered_array))
for i in numpy_filtered_array:
    print(i)

4
[ 0  1  3  4  7  9 10 11 12 14]
[15 17 25 27 30 35]
[ 2  5  6  8 13]
[16 18 19 20 21 22 23 24 26 28 29 31 32 33 34]


In [7]:

length_of_array = total_students - (total_students%int(desired_group_size))
print(length_of_array)

forced_array = np.arange(0, length_of_array,1)
forced_array.shape

35


(35,)

In [8]:
print(forced_array[6])

6


In [9]:
reshape_array = forced_array.reshape(int (desired_group_size),int(number_of_teams))
print(reshape_array.shape)

reshape_array
### Work on splitting the femal teams into two items in the array and reshape from there. 
#SO two females get automatically get selected into the teams - then reshape array again? maybe it needs doing before the reshape!

(5, 7)


array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [10]:
#This Works!!!!

for i in reshape_array[0]:
    print('Team ', i, ':', reshape_array[:,i])#a plus 1 is added to make up the numbers so they can be called in the df.
    
    print()

Team  0 : [ 0  7 14 21 28]

Team  1 : [ 1  8 15 22 29]

Team  2 : [ 2  9 16 23 30]

Team  3 : [ 3 10 17 24 31]

Team  4 : [ 4 11 18 25 32]

Team  5 : [ 5 12 19 26 33]

Team  6 : [ 6 13 20 27 34]



In [11]:
#THIS WORKS!!!! DO NOT TOUCH
for i in reshape_array[0]:
    print('Team ', i, ':', reshape_array[:,i]+1)#a plus 1 is added to make up the numbers so they can be called in the df.
    num = reshape_array[:,i]+1
    for j in num:
        print(dfrandom.iloc[j])#This line to get the values from the dictionary item!!!
        print('--------------------')
    print('\n\n\n##########################################################################')  
    print()


Team  0 : [ 1  8 15 22 29]
Filter                                                                1
Gender                                                                f
SURNAME                                                        LAWRENCE
FIRST NAME                                                         JAZZ
E-MAIL NAME                                       ry22547@bristol.ac.uk
COMMON USERNAME                                                 ry22547
STUDENT NUMBER                                                  2310326
ENROLMENT STATUS                                      Registered online
PROGRAMME OF STUDY    Immersive Arts (Virtual and Augmented Reality)...
MODE OF ATTENDANCE                                            Full Time
Name: 1, dtype: object
--------------------
Filter                                                                1
Gender                                                                f
SURNAME                                                          

In [12]:
#You need to add the remainder people in!
print(remainder_people)
if remainder_people > 0:
    start = len(forced_array)
    stop = len(forced_array) +remainder_people
    step = 1

    wildcards = np.arange(start,stop,step)
elif remainder_people == 0:
    wildcards = 0
print(len(forced_array))
wildcards

1
35


array([35])

In [13]:
for i in wildcards:
    print('Remaining wildcards for assignment: ')
    print('\n\n')
    print(dfrandom.iloc[i])

Remaining wildcards for assignment: 



Filter                                                                1
Gender                                                                m
SURNAME                                                              MA
FIRST NAME                                                      ZHENKUN
E-MAIL NAME                                       to22544@bristol.ac.uk
COMMON USERNAME                                                 to22544
STUDENT NUMBER                                                  2299724
ENROLMENT STATUS                                      Registered online
PROGRAMME OF STUDY    Immersive Arts (Virtual and Augmented Reality)...
MODE OF ATTENDANCE                                      Full Time - F85
Name: 35, dtype: object


#todo - make output suitable for Keirs selection programme - fine tuning for output with Sam
import sys
sys.stdout = open("wildcardtest.txt", "w")
for i in wildcards:
    print('Remaining wildcards for assignment: ')
    print('\n\n')
    print(df.iloc[i])

sys.stdout.close()

In [14]:
newindex = []
for i in reshape_array[0]:
    #print('Team ', i, ':', reshape_array[:,i]+1)
    newindex.extend(reshape_array[:,i])

newindex.extend(wildcards)
print(newindex)
print(len(newindex))

[0, 7, 14, 21, 28, 1, 8, 15, 22, 29, 2, 9, 16, 23, 30, 3, 10, 17, 24, 31, 4, 11, 18, 25, 32, 5, 12, 19, 26, 33, 6, 13, 20, 27, 34, 35]
36


In [15]:
#THIS WORKS!!!! DO NOT TOUCH
df2 = dfrandom
#THIS WORKS!!!
df3 = df2.reindex(newindex)
df3
df3.to_excel("36ImmersiveTeamsIEEoutput23_9_22.xlsx")

In [21]:
#THIS WORKS!!!! DO NOT TOUCH
for i in reshape_array[0]:
    print('Team ', i, ':', reshape_array[:,i])#a plus 1 is added to make up the numbers so they can be called in the df.
    num = reshape_array[:,i]
    for j in num:
        print(dfrandom.iloc[j])#This line to get the values from the dictionary item!!!
        print('--------------------')
    print('\n\n\n##########################################################################')  
    print()


Team  0 : [  0  31  62  93 124 155]
Gender                                            m
SURNAME                                     BEESTON
FIRST NAME                                     ALEX
E-MAIL NAME                   eg19162@bristol.ac.uk
COMMON USERNAME                             eg19162
STUDENT NUMBER                              1816863
ENROLMENT STATUS                 Registered student
PROGRAMME OF STUDY    Mechanical Engineering (MEng)
MODE OF ATTENDANCE                        Full Time
Name: 0, dtype: object
--------------------
Gender                                            m
SURNAME                               TAUHEED IRFAN
FIRST NAME                                   NABEEL
E-MAIL NAME                   fq19702@bristol.ac.uk
COMMON USERNAME                             fq19702
STUDENT NUMBER                              1900331
ENROLMENT STATUS                 Registered student
PROGRAMME OF STUDY    Mechanical Engineering (MEng)
MODE OF ATTENDANCE                  

Name: 91, dtype: object
--------------------
Gender                                            m
SURNAME                                         RAJ
FIRST NAME                                    ISHAN
E-MAIL NAME                   fz19711@bristol.ac.uk
COMMON USERNAME                             fz19711
STUDENT NUMBER                              1953429
ENROLMENT STATUS                 Registered student
PROGRAMME OF STUDY    Mechanical Engineering (MEng)
MODE OF ATTENDANCE                        Full Time
Name: 122, dtype: object
--------------------
Gender                                                           m
SURNAME                                                        DIK
FIRST NAME                                                    IVAN
E-MAIL NAME                                  or18049@bristol.ac.uk
COMMON USERNAME                                            or18049
STUDENT NUMBER                                             1764257
ENROLMENT STATUS                       

In [22]:
#You need to add the remainder people in!
print(remainder_people)
if remainder_people > 0:
    start = len(forced_array)
    stop = len(forced_array) +remainder_people
    step = 1
wildcards = np.arange(start,stop,step)
wildcards

5


array([186, 187, 188, 189, 190])

In [ ]:
""" 
1. By subject
2. No lone female working per group if possible
3. Teams of 6
4. Distribution of international students 
- Andy check if you randomised through indexing ? Thats go tot be first step. Normally F-85 tag
5. Immersive arts and technologies is 38 students - compulsory  
- these are to be isolated and a 50/50 split immersive arts and technologies- split before runnign programme. 
- 3 immersives and 3 tech in each group. 
6. Build a name randomiser into it to mix them up so they are not alphabetical - then run the whole thing again. 
"""

In [18]:
print(dfrandom)

    Gender   SURNAME  FIRST NAME            E-MAIL NAME COMMON USERNAME  \
0        m   BEESTON        ALEX  eg19162@bristol.ac.uk         eg19162   
1        m  ABRAHAMS       FELIX  tw19532@bristol.ac.uk         tw19532   
2        m    FULTON        RORY  pj19298@bristol.ac.uk         pj19298   
3        m      ZHAO         SHI  bn19351@bristol.ac.uk         bn19351   
4        f   SIEMPOU      KALLIA  op19491@bristol.ac.uk         op19491   
..     ...       ...         ...                    ...             ...   
186      m    FLOROS  ALEXANDROS  yj19200@bristol.ac.uk         yj19200   
187      m   CHAPMAN       JAMIE  pd19431@bristol.ac.uk         pd19431   
188      m     ELLIS         MAX  ju19470@bristol.ac.uk         ju19470   
189      m       YEO     CHESTER  gn19699@bristol.ac.uk         gn19699   
190      m     PATEL        NEAL  kb19792@bristol.ac.uk         kb19792   

    STUDENT NUMBER      ENROLMENT STATUS  \
0          1816863    Registered student   
1          

In [23]:
print(df_full_array[190])



['m' 'PATEL' 'NEAL' 'kb19792@bristol.ac.uk' 'kb19792' '\xa01902060'
 'Registered student' 'Aerospace Engineering (MEng)' 'Full Time']


In [46]:
print(dfrandom)

    Gender     SURNAME FIRST NAME            E-MAIL NAME COMMON USERNAME  \
0        f  ABETH NEGO   JEEVITHA  cv22601@bristol.ac.uk         cv22601   
1        f         ZHA      QIUYU  ba19677@bristol.ac.uk         ba19677   
2        f    BARBIERI  FRANCESCA  rt19221@bristol.ac.uk         rt19221   
3        f       PARRY    GEORGIA  rh19536@bristol.ac.uk         rh19536   
4        f       SALEH     RAHMAH  ox19852@bristol.ac.uk         ox19852   
..     ...         ...        ...                    ...             ...   
186      m     MOFFETT       FINN  du19035@bristol.ac.uk         du19035   
187      m        WONG     KELVIN  sa19529@bristol.ac.uk         sa19529   
188      m         RAJ      ISHAN  fz19711@bristol.ac.uk         fz19711   
189      m      LE COZ   BENJAMIN  go19111@bristol.ac.uk         go19111   
190      m  KARAJGIKAR      ROHIT  xa18708@bristol.ac.uk         xa18708   

    STUDENT NUMBER    ENROLMENT STATUS  \
0          2243764   Registered online   
1  

In [45]:
print(gendergroups)

{'Aerospace Engineering (MEng)': Int64Index([  2,   7,  14,  17,  30,  39,  40,  41,  44,  45,  59,  65,  67,
             70,  71,  74,  76,  77,  82,  84,  85,  91,  98, 118, 127, 131,
            133, 137, 138, 151, 153, 167, 169, 171, 173, 179, 182, 187],
           dtype='int64'), 'Aerospace Engineering with Study Abroad (MEng)': Int64Index([31, 83], dtype='int64'), 'Aerospace Engineering with a year in Industry (MEng)': Int64Index([190], dtype='int64'), 'Biomedical Engineering (MSc)': Int64Index([0, 26, 32, 35, 128], dtype='int64'), 'Civil Engineering (MEng)': Int64Index([  1,   5,   8,  29,  33,  34,  38,  46,  56,  57,  60,  69,  89,
             95, 102, 114, 115, 124, 125, 129, 143, 144, 148, 150, 160, 183],
           dtype='int64'), 'Civil Engineering with Study in Continental Europe (MEng)': Int64Index([4], dtype='int64'), 'Computer Science and Electronics (MEng)': Int64Index([24, 121, 180], dtype='int64'), 'Electrical and Electronic Engineering (MEng)': Int64Index([9, 50,